@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Administrator" as ADM
participant ":RegisterClientUI" as UI
participant ":ClientController" as CTRL
participant ":ClientService" as SRV
participant "ClientException" as EXC
participant "Repositories" as REPS
participant "repositories\n:Repositories" as REP
participant "clientRepository:\nClientRepository" as clientRepository
participant "addressRepository:\nAddressRepository" as addressRepository
participant "client:\nClient" as CLIENT
participant "address:\nAddress" as ADDRESS
participant "Validator" as VAL

title Update Client Sequence

activate ADM
    ADM -> UI : asks to update a client
    activate UI

        UI -> CTRL** : create

        UI -> CTRL : getAllClients()
        activate CTRL
            CTRL -> SRV : getClients()
            activate SRV

                SRV -> REPS : getInstance()
                activate REPS
                REPS --> SRV: repositories
                deactivate REPS
                SRV -> REP : getClientRepository()
                activate REP
                REP --> SRV : clientRepository
                deactivate REP

                SRV -> clientRepository : getAll()
                activate clientRepository
                clientRepository --> SRV : clients
                deactivate clientRepository
            SRV --> CTRL : clients
            deactivate SRV
        CTRL --> UI : clients
        deactivate CTRL
    UI --> ADM : shows the list of clients and requests confirmation
    deactivate UI

    ADM -> UI : confirms that he wants to update a client
    activate UI

        UI --> ADM : requests Client ID
    deactivate UI

    ADM -> UI : provides requested ID
    activate UI

        UI -> CTRL : getClientByID(clientID)
        activate CTRL
            CTRL -> SRV : getClientByID(clientID)
            activate SRV

                SRV -> REP : getClientRepository()
                activate REP
                REP --> SRV : clientRepository
                deactivate REP
                SRV -> clientRepository : getById(clientID))
                activate clientRepository
                clientRepository --> SRV : client
                deactivate clientRepository
                alt client == null
                    SRV -> EXC: throw clientNotFound(clientID)
                    activate EXC
                    EXC --> SRV: Exception Thrown
                    deactivate EXC
                    SRV --> CTRL: show error message (Client does not exist)
                    CTRL --> UI: show error message (Client does not exist)
                else
            SRV --> CTRL : client
            deactivate SRV
        CTRL --> UI : client
        deactivate CTRL
        end

        UI --> ADM : shows all data of client and requests data to be update or error message
    deactivate UI

    ADM -> UI : types/selects requested data
    activate UI
        UI -> CTRL: updateClient(client, name, vatin, street, zipCode, town, country, phoneNumber, email, type)
        activate CTRL
            CTRL -> SRV: updateClient(client, name, vatin, street, zipCode, town, country, phoneNumber, email, type)
            activate SRV

                SRV -> VAL: isValidData(phoneNumber, email, zipCode)
                activate VAL
                VAL --> SRV: true/false
                deactivate VAL

                alt false

                    SRV -> EXC: throw invalidData()
                    activate EXC
                    EXC --> SRV: Exception Thrown
                    deactivate EXC
                    SRV --> CTRL: show error message (Invalid data)

                    CTRL --> UI: show error message (Invalid data)
                    deactivate VAL
                else

                    SRV -> REP: getAddressRepository()
                    activate REP
                    REP --> SRV: addressRepository
                    deactivate REP

                    SRV -> addressRepository: findAddress(address)
                    activate addressRepository
                    addressRepository --> SRV: address
                    deactivate addressRepository
                    alt address == null
                        SRV -> ADDRESS** : create(address)
                        SRV -> addressRepository: save(address)
                        activate addressRepository
                        addressRepository --> SRV: address
                        deactivate addressRepository
                    end

                    SRV -> CLIENT: setAddress(address)
                    activate CLIENT
                    CLIENT --> SRV :
                    deactivate CLIENT
                    SRV -> CLIENT: setName(name)
                    activate CLIENT
                    CLIENT --> SRV :
                    deactivate CLIENT
                    SRV -> CLIENT: setVatin(vatin)
                    activate CLIENT
                    CLIENT --> SRV :
                    deactivate CLIENT
                    SRV -> CLIENT: setPhoneNumber(phoneNumber)
                    activate CLIENT
                    CLIENT --> SRV :
                    deactivate CLIENT
                    SRV -> CLIENT: setEmail(email)
                    activate CLIENT
                    CLIENT --> SRV :
                    deactivate CLIENT
                    SRV -> CLIENT: setType(type)
                    activate CLIENT
                    CLIENT --> SRV :
                    deactivate CLIENT

                    SRV -> REP: getClientRepository()
                    activate REP
                    REP --> SRV: clientRepository
                    deactivate REP
                    SRV -> clientRepository: update(client)
                    activate clientRepository
                    alt system error
                        clientRepository --> SRV: Database error

                        SRV --> CTRL: show error message (Database error)

                        CTRL --> UI: show error message (Database error)
                    else
                        clientRepository --> SRV: client
                        deactivate clientRepository
                        SRV --> CTRL: client
                        deactivate SRV
                        CTRL --> UI: client
                        deactivate CTRL
                    end
                end

    UI --> ADM: shows all data and displays operation success or error message
    deactivate UI

deactivate ADM
@enduml
