@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

package "UI" {
    class RegisterOrderUI {
    }
}

package "Controller" {
    class ClientController {
        +getAllClients() : List<Client>
        +getClientById(clientID) : Client
    }

    class OrderController {
        +registerOrder(client, orderID, deliveryStreet, deliveryZipCode, deliveryTown, deliveryCountry, orderDate, deliveryDate, price, productIdQuantityMap) : Order
    }

    class ProductController {
        +getProducts() : List<Product>
    }
}

package "Service" {
    class ClientService {
        +getClients() : List<Client>
        +getClientById(clientID) : Client
    }

    class OrderService {
        +registerOrder(client, orderID, deliveryStreet, deliveryZipCode, deliveryTown, deliveryCountry, orderDate, deliveryDate, price, productQuantityMap)
        -calculatePrice(productQuantityMap) : int
    }

    class ProductService {
        +getProducts() : List<Product>
        +getProductByID(productID) : Product
    }
}

package "Repository" {
    class Repositories {
        -Repositories()
        +getInstance() : Repositories
        +getClientRepository() : ClientRepository
        +getAddressRepository() : AddressRepository
        +getProductRepository() : ProductRepository
        +getOrderRepository() : OrderRepository
    }

    class ClientRepository {
        +getAll() : List<Client>
        +getById(clientID) : Client
    }

    class AddressRepository {
        +findAddress(street, zipCode, town, country) : Address
        +getAddressCount() : int
        +save(deliveryAddress) : boolean
    }

    class ProductRepository {
        +getAll() : List<Product>
        +getProductByID(productID) : Product
    }

    class OrderRepository {
        +getOrderExists(orderID) : boolean
        +save(order, client) : boolean
    }
}

package "Model" {
    class Client {
        -clientID : int
        -address : Address
        -name : String
        -vatin : String
        -phoneNumber : int
        -email : String
        -type : CompanyType
        -state : EntityState
        -orders : List<Order>
        +Client(clientID, name, address, vatin, phoneNumber, email, type)
    }

    class Address {
        -id : int
        -street : String
        -zipCode : String
        -town : String
        -country : String
        +Address(id, street, zipCode, town, country)
    }

    class Order {
        -orderID : int
        -deliveryAddress : Address
        -orderDate : Date
        -deliveryDate : Date
        -price : double
        -state : ProcessState
        -productQuantity : Map<Product, Integer>
        +Order(orderID, deliveryAddress, orderDate, deliveryDate, price, productQuantity)
    }

    enum ProcessState {
        PENDING
        CONFIRMED
    }

    class Part {
        -id : String
        -name : String
        -description : String
        +Part(id, name, description)
    }

    class Product {
        -category : ProductCategory
        -capacity : int
        -size : int
        -color : String
        -price : double
        +Product(id, name, description, category, capacity, size, color, price)
    }
}

package "Exception" {
    class ClientException {
        +clientNotFound(clientID) : ClientException
    }

    class ProductException {
        +productNotFound(productID) : ProductException
    }

    class OrderException {
        +orderAlreadyExists(orderID) : OrderException
        +invalidDeliveryDate() : OrderException
        +invalidZipCode() : OrderException
    }

    class RuntimeException
}

package "Commom" {
    class Validator {
        +isValidZipCode(zipCode) : boolean
    }
}


RegisterOrderUI ..> ClientController
RegisterOrderUI ..> OrderController
RegisterOrderUI ..> ProductController
ClientController ..> ClientService
OrderController ..> OrderService
OrderController ..> ProductService
ProductController ..> ProductService
ClientService ..> Repositories : repositories
OrderService ..> Repositories : repositories
ProductService ..> Repositories : repositories
ClientService ..> ClientRepository : clientRepository
OrderService ..> OrderRepository : orderRepository
OrderService ..> AddressRepository : addressRepository
ProductService ..> ProductRepository : productRepository
ClientService ..> Client : client
OrderService ..> Order : order
OrderService ..> Address : address
ProductService ..> Product : product
Repositories --> Repositories : instance
Repositories "1" --> "1" ClientRepository : clientRepository
Repositories "1" --> "1" AddressRepository : addressRepository
Repositories "1" --> "1" OrderRepository : orderRepository
Repositories "1" --> "1" ProductRepository : productRepository
ClientRepository "1" --> "*" Client : categories
AddressRepository "1" --> "*" Address : categories
OrderRepository "1" --> "*" Order : categories
ProductRepository "1" --> "*" Product : categories
Client "*" --> "1" Address : has
Client "1" --> "*" Order : has
Order "*" --> "1" Address : has
Order "*" --> "1..*" Product : has
Product --|> Part
Order "*" --> "1" ProcessState : has
ClientService ..> ClientException : throws
ClientException --|> RuntimeException
OrderService ..> OrderException : throws
OrderException --|> RuntimeException
ProductService ..> ProductException : throws
ProductException --|> RuntimeException
OrderService ..> Validator : uses

@enduml
