@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - US015

class ProductionManager {
}

class RawMaterial {
    id
    name
    description
    currentStock
    minimumStock
}

ProductionManager "1" -- "1..*" RawMaterial : consult >

@enduml
