@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model - US024

class PlantFloorManager {
}

class OperationType {
    id
    name
}

class CanBeDoneAt {
    setupTime
}

class WorkstationType {
    id
    name
}

PlantFloorManager "1" -- "1..*" CanBeDoneAt : update >
OperationType "1" -- "*" CanBeDoneAt : attributed to >
CanBeDoneAt "*" -- "1" WorkstationType : requires >

@enduml
