@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Production Manager" as PM
participant ":ConsultActiveOrdersUI" as UI
participant ":OrderController" as CTRL
participant ":OrderService" as SRV
participant "Repositories" as REPS
participant "repositories\n:Repositories" as REP
participant "orderRepository:\nOrderRepository" as orderRepository
participant "order:\nOrder" as ORDER
participant "activeOrders:\nList<Order>" as activeOrders

title Client Status Sequence

activate PM
    PM -> UI : requests active orders
    activate UI

        UI -> CTRL** : create

        UI -> CTRL : consultActiveOrders()
        activate CTRL
            CTRL -> SRV : activeOrders()
            activate SRV

                SRV -> REPS : getInstance()
                activate REPS
                REPS --> SRV: repositories
                deactivate REPS
                SRV -> REP : getOrderRepository()
                activate REP
                REP --> SRV : orderRepository
                deactivate REP

                SRV -> orderRepository : getAll()
                activate orderRepository
            alt system error
                        orderRepository --> SRV: Database error

                        SRV --> CTRL: show error message (Database error)

                        CTRL --> UI: show error message (Database error)
            else
                        orderRepository --> SRV: orders
                        deactivate orderRepository

            SRV -> activeOrders** : create

            loop For each order in orders

                        SRV -> ORDER : getDeliveryDate()
                        activate ORDER
                        ORDER --> SRV : deliveryDate
                        deactivate ORDER

                        alt delivery date after current date
                            SRV -> activeOrders : add(order)
                            activate activeOrders
                            activeOrders --> SRV :
                            deactivate activeOrders
                        end alt
                    end loop

                    SRV --> CTRL : activeOrders
                end alt
                deactivate SRV

            CTRL --> UI : activeOrders
            deactivate CTRL

        UI --> PM : shows the list of active orders or error message
        deactivate UI

deactivate PM
@enduml
