@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Production Manager" as PM
participant ":System" as System

activate PM

    PM -> System : asks to change the category of a product
    activate System

        System --> PM : shows the list of products and asks for confirmation
    deactivate System

    PM -> System : confirms that he changes the category of a product
    activate System

        System --> PM : shows the list of categories
    deactivate System

    PM -> System : selects an option (new/existing category)
    activate System

    alt new category

            System --> PM : requests category name
            deactivate System

            PM -> System : provides category name
            activate System

            System -> System : saves category
                alt system error
                    System --> PM : shows error message (Database error)
                    deactivate System
                end

    else existing category

        System --> PM : requests category ID
        deactivate System

        PM -> System : provides category ID
        activate System

        System -> System : checks if category already exists
            alt category does not exist
                    System --> PM : shows error message (Category does not exist)
                deactivate System
            end
    end

        System --> PM : requests product id
    deactivate System

    PM -> System : types requested id
    activate System

    System -> System : checks if product already exists
        alt product does not exist
                System --> PM : shows error message (Product does not exist)
            deactivate System
        else

                System -> System : change the category of a product
                alt system error
                    System --> PM : shows error message (Database error)
                    deactivate System
                else success
                    System --> PM : shows all data and displays operation success
                    deactivate System
                end
        end
@enduml
